spring:
  datasource:
    url: jdbc:h2:mem:itg-dev-db
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: ERROR
    hibernate: ERROR
    org.springframework: INFO
    com.itg.exam: INFO